### ISSUE TITLE
Combat System

### ISSUE THREAD

**Issue by SkySlicer500** [SkySlicer500/TextGame#4]
We need to come up with a specific way for combat to work as well as when enemies will be encountered. Already planning on making NPCs able to be attacked and killed.

**Comment by SkySlicer500** [comment]
We can include the NPCs being attacked and killed, but we can also have enemies attack the player immediately when they enter a room. Other enemies can be spawned in by the event system.

**Comment by TheEpicTree** [comment]
turn based combat, health is 100% at the beginning of every battle

**Comment by SkySlicer500** [comment]
Combat system has been implemented and totally 100% tested, definitely
